### ISSUE TITLE
Sum is not correct.

### ISSUE THREAD

**Issue by sapabg** [s3c4/angular-ts-math#1] opened 2019-02-21 14:31 UTC
using angularMath.sum(n1, n2, n3, ...); returns the same sum as it would if I use a simple + operator which returns the wrong sum. Example:
ler arr =[0.32, 0.16, 0.16, 0.16, 0.02, 0.16];
angularMath.sum(...arr) returns 0.9800000000000001

**Comment by s3c4** [comment] 2022-07-07 21:55
The issue is fixed in version 2.0.0

**Closed as completed by s3c4** 2022-07-07 21:55 UTC
